version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        # GF_AUTH_DISABLE_LOGIN_FORM: "true"
      volumes:
        - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  postgres-data:
  grafana-data:

