global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pg-stat-scraper"
    metrics_path: /pg_stat_metrics # Endpoint exposed by Go scraper
    static_configs:
      - targets: ["host.docker.internal:8080"] # Go scraper's address
